import {
  Category,
  Certificate,
  Course,
  Lesson,
  Notification,
  Podcast,
  Profile,
  Quiz,
  QuizQuestion,
  Template,
} from '../types';

const now = new Date().toISOString();

export const demoProfile: Profile = {
  id: 'demo-user',
  full_name: 'GTC Learner',
  avatar_url: null,
  bio: 'Learning Excel, dashboards, and data analysis with GTC Academy.',
  plan: 'premium_monthly',
  role: 'student',
  preferred_language: 'fr',
  theme_preference: 'system',
  xp_points: 1240,
  learning_streak: 7,
  badges: ['starter', 'consistent_learner'],
  achievements: ['first_course_started'],
  streak_days: 7,
  last_active_at: now,
  country: 'CD',
  created_at: now,
  updated_at: now,
};

export const demoCategories: Category[] = [
  { id: 'cat-excel', name: 'Excel', slug: 'excel', icon: 'spreadsheet', color: '#0A6EFF', sort_order: 1 },
  { id: 'cat-data', name: 'Data Analysis', slug: 'data', icon: 'chart', color: '#00C896', sort_order: 2 },
  { id: 'cat-bi', name: 'Business Intelligence', slug: 'bi', icon: 'dashboard', color: '#7C3AED', sort_order: 3 },
  { id: 'cat-sheets', name: 'Google Sheets', slug: 'sheets', icon: 'bolt', color: '#FF6B35', sort_order: 4 },
  { id: 'cat-powerbi', name: 'Power BI', slug: 'power-bi', icon: 'dashboard', color: '#F2C811', sort_order: 5 },
  { id: 'cat-programming', name: 'Programming', slug: 'programming', icon: 'code', color: '#00C8FF', sort_order: 6 },
  { id: 'cat-web', name: 'Web Development', slug: 'web-development', icon: 'globe', color: '#00E09A', sort_order: 7 },
  { id: 'cat-mobile', name: 'Mobile Development', slug: 'mobile-development', icon: 'phone', color: '#9B73F8', sort_order: 8 },
  { id: 'cat-ai', name: 'Artificial Intelligence', slug: 'artificial-intelligence', icon: 'spark', color: '#FFB020', sort_order: 9 },
  { id: 'cat-cad', name: 'CAD and Engineering', slug: 'cad-engineering', icon: 'box', color: '#FF5E5E', sort_order: 10 },
  { id: 'cat-cloud', name: 'Cloud Computing', slug: 'cloud-computing', icon: 'cloud', color: '#38BDF8', sort_order: 11 },
  { id: 'cat-cyber', name: 'Cybersecurity', slug: 'cybersecurity', icon: 'shield', color: '#22C55E', sort_order: 12 },
  { id: 'cat-uiux', name: 'UI/UX Design', slug: 'ui-ux-design', icon: 'palette', color: '#F472B6', sort_order: 13 },
  { id: 'cat-networking', name: 'Networking', slug: 'networking', icon: 'network', color: '#A78BFA', sort_order: 14 },
];

export const demoCourses: Course[] = [
  {
    id: 'course-excel-foundations',
    category_id: 'cat-excel',
    title: 'Excel Foundations for Business',
    slug: 'excel-foundations',
    description: 'Build clean spreadsheets, use essential formulas, and prepare reports with confidence.',
    thumbnail_url: null,
    preview_video: null,
    level: 'beginner',
    is_premium: false,
    is_published: true,
    enrolled_count: 1240,
    rating: 4.8,
    rating_count: 312,
    price: 0,
    currency: 'USD',
    duration_minutes: 180,
    delivery_modes: ['online', 'in_person'],
    certificate_available: true,
    final_exam_available: true,
    prerequisites: ['Basic computer usage'],
    learning_objectives: ['Build clean spreadsheets', 'Use essential formulas', 'Prepare business reports'],
    skills_acquired: ['Spreadsheet structure', 'SUMIFS', 'XLOOKUP', 'Reporting basics'],
    popularity_score: 1240,
    lessons_count: 6,
    sort_order: 1,
    created_at: now,
    category: demoCategories[0],
    progress: 62,
    is_enrolled: true,
  },
  {
    id: 'course-dashboard-masterclass',
    category_id: 'cat-bi',
    title: 'Dashboard Masterclass',
    slug: 'dashboard-masterclass',
    description: 'Design KPI dashboards that managers can read quickly and use for decisions.',
    thumbnail_url: null,
    preview_video: null,
    level: 'intermediate',
    is_premium: true,
    is_published: true,
    enrolled_count: 820,
    rating: 4.9,
    rating_count: 201,
    price: 49,
    currency: 'USD',
    duration_minutes: 360,
    delivery_modes: ['online', 'in_person'],
    certificate_available: true,
    final_exam_available: true,
    prerequisites: ['Excel basics', 'Data cleaning basics'],
    learning_objectives: ['Design KPI dashboards', 'Choose useful charts', 'Present metrics clearly'],
    skills_acquired: ['KPI design', 'Dashboard layout', 'Executive reporting'],
    popularity_score: 980,
    lessons_count: 8,
    sort_order: 2,
    created_at: now,
    category: demoCategories[2],
    progress: 18,
    is_enrolled: true,
  },
  {
    id: 'course-data-cleaning',
    category_id: 'cat-data',
    title: 'Data Cleaning Workflow',
    slug: 'data-cleaning-workflow',
    description: 'Turn messy exports into reliable analysis tables using repeatable cleaning steps.',
    thumbnail_url: null,
    preview_video: null,
    level: 'intermediate',
    is_premium: false,
    is_published: true,
    enrolled_count: 965,
    rating: 4.7,
    rating_count: 176,
    price: 0,
    currency: 'USD',
    duration_minutes: 240,
    delivery_modes: ['online'],
    certificate_available: true,
    final_exam_available: true,
    prerequisites: ['Basic spreadsheets'],
    learning_objectives: ['Audit raw exports', 'Clean messy data', 'Create repeatable workflows'],
    skills_acquired: ['Data profiling', 'Deduplication', 'Cleaning documentation'],
    popularity_score: 965,
    lessons_count: 5,
    sort_order: 3,
    created_at: now,
    category: demoCategories[1],
    progress: 0,
    is_enrolled: false,
  },
  {
    id: 'course-sheets-automation',
    category_id: 'cat-sheets',
    title: 'Google Sheets Automation',
    slug: 'google-sheets-automation',
    description: 'Use formulas and Apps Script basics to automate recurring reporting work.',
    thumbnail_url: null,
    preview_video: null,
    level: 'advanced',
    is_premium: true,
    is_published: true,
    enrolled_count: 540,
    rating: 4.6,
    rating_count: 98,
    price: 39,
    currency: 'USD',
    duration_minutes: 300,
    delivery_modes: ['online'],
    certificate_available: true,
    final_exam_available: true,
    prerequisites: ['Google Sheets basics'],
    learning_objectives: ['Automate recurring reports', 'Use formulas efficiently', 'Understand Apps Script basics'],
    skills_acquired: ['Sheets automation', 'Formula design', 'Apps Script fundamentals'],
    popularity_score: 620,
    lessons_count: 7,
    sort_order: 4,
    created_at: now,
    category: demoCategories[3],
    progress: 0,
    is_enrolled: false,
  },
  {
    id: 'course-python-foundations',
    category_id: 'cat-programming',
    title: 'Python Foundations for Technology Careers',
    slug: 'python-foundations-technology-careers',
    description: 'Learn programming basics with practical exercises for automation, data, and web foundations.',
    thumbnail_url: null,
    preview_video: null,
    level: 'beginner',
    is_premium: false,
    is_published: true,
    enrolled_count: 710,
    rating: 4.7,
    rating_count: 143,
    price: 0,
    currency: 'USD',
    duration_minutes: 420,
    delivery_modes: ['online'],
    certificate_available: true,
    final_exam_available: true,
    prerequisites: ['Basic computer usage'],
    learning_objectives: ['Write Python scripts', 'Understand variables and functions', 'Automate simple tasks'],
    skills_acquired: ['Python syntax', 'Problem solving', 'Automation basics'],
    popularity_score: 740,
    lessons_count: 9,
    sort_order: 5,
    created_at: now,
    category: demoCategories[5],
    progress: 0,
    is_enrolled: false,
  },
  {
    id: 'course-autocad-professional-basics',
    category_id: 'cat-cad',
    title: 'AutoCAD Professional Basics',
    slug: 'autocad-professional-basics',
    description: 'Build technical drawing confidence for engineering, construction, and industrial projects.',
    thumbnail_url: null,
    preview_video: null,
    level: 'beginner',
    is_premium: true,
    is_published: true,
    enrolled_count: 390,
    rating: 4.6,
    rating_count: 74,
    price: 59,
    currency: 'USD',
    duration_minutes: 540,
    delivery_modes: ['online', 'in_person'],
    certificate_available: true,
    final_exam_available: true,
    prerequisites: ['Basic computer usage'],
    learning_objectives: ['Use drafting tools', 'Create clean plans', 'Export professional drawings'],
    skills_acquired: ['2D drafting', 'Layers', 'Dimensioning', 'Plot setup'],
    popularity_score: 480,
    lessons_count: 10,
    sort_order: 6,
    created_at: now,
    category: demoCategories[9],
    progress: 0,
    is_enrolled: false,
  },
];

export const demoLessonsByCourse: Record<string, Lesson[]> = {
  'course-excel-foundations': [
    {
      id: 'lesson-excel-1',
      course_id: 'course-excel-foundations',
      title: 'Workbook structure and clean tables',
      description: 'Set up spreadsheets that are easy to audit and reuse.',
      type: 'article',
      video_url: null,
      pdf_url: null,
      content: 'Use one table per sheet, clear headers, consistent formats, and named ranges for key inputs.',
      duration_secs: 540,
      order_index: 1,
      is_free: true,
      is_published: true,
      completed: true,
    },
    {
      id: 'lesson-excel-2',
      course_id: 'course-excel-foundations',
      title: 'Essential formulas',
      description: 'SUMIFS, COUNTIFS, XLOOKUP, IFERROR, and clean references.',
      type: 'article',
      video_url: null,
      pdf_url: null,
      content: 'Start with formulas that answer a business question, then make them readable and testable.',
      duration_secs: 720,
      order_index: 2,
      is_free: true,
      is_published: true,
      completed: false,
    },
  ],
  'course-dashboard-masterclass': [
    {
      id: 'lesson-dashboard-1',
      course_id: 'course-dashboard-masterclass',
      title: 'Choose the right KPIs',
      description: 'Separate vanity metrics from decision metrics.',
      type: 'article',
      video_url: null,
      pdf_url: null,
      content: 'A strong dashboard starts with the decision it supports, not the chart style.',
      duration_secs: 680,
      order_index: 1,
      is_free: true,
      is_published: true,
      completed: false,
    },
  ],
  'course-data-cleaning': [
    {
      id: 'lesson-cleaning-1',
      course_id: 'course-data-cleaning',
      title: 'Audit raw exports',
      description: 'Find missing values, duplicated rows, and inconsistent labels.',
      type: 'article',
      video_url: null,
      pdf_url: null,
      content: 'Never clean blindly. Profile the file first, then document the cleaning rules.',
      duration_secs: 600,
      order_index: 1,
      is_free: true,
      is_published: true,
      completed: false,
    },
  ],
  'course-sheets-automation': [
    {
      id: 'lesson-sheets-1',
      course_id: 'course-sheets-automation',
      title: 'Automation opportunities',
      description: 'Identify repetitive tasks that are worth automating.',
      type: 'article',
      video_url: null,
      pdf_url: null,
      content: 'Automate repeated imports, formatting, notifications, and consolidation work.',
      duration_secs: 590,
      order_index: 1,
      is_free: false,
      is_published: true,
      completed: false,
    },
  ],
};

export const demoQuizzesByCourse: Record<string, Quiz[]> = {
  'course-excel-foundations': [
    {
      id: 'quiz-excel-foundations',
      course_id: 'course-excel-foundations',
      title: 'Excel Foundations Quiz',
      description: 'Check the key spreadsheet habits from this course.',
      pass_score: 80,
      is_premium: false,
    },
  ],
  'course-dashboard-masterclass': [
    {
      id: 'quiz-dashboard-masterclass',
      course_id: 'course-dashboard-masterclass',
      title: 'Dashboard Design Quiz',
      description: 'Validate your KPI and layout decisions.',
      pass_score: 80,
      is_premium: true,
    },
  ],
};

export const demoQuestionsByQuiz: Record<string, QuizQuestion[]> = {
  'quiz-excel-foundations': [
    {
      id: 'question-excel-1',
      quiz_id: 'quiz-excel-foundations',
      question: 'Which function is best for summing sales by region and month?',
      options: ['SUM', 'SUMIFS', 'COUNTIF', 'LEFT'],
      correct_index: 1,
      explanation: 'SUMIFS can apply multiple criteria, such as region and month, before summing sales.',
      order_index: 1,
    },
    {
      id: 'question-excel-2',
      quiz_id: 'quiz-excel-foundations',
      question: 'What is the safest way to avoid broken formulas when a lookup value is missing?',
      options: ['Hide the row', 'Use IFERROR around the lookup', 'Delete missing data', 'Format as currency'],
      correct_index: 1,
      explanation: 'IFERROR lets you return a clean fallback message or value when the lookup fails.',
      order_index: 2,
    },
    {
      id: 'question-excel-3',
      quiz_id: 'quiz-excel-foundations',
      question: 'Why should raw data and reports usually stay on separate sheets?',
      options: ['It looks bigger', 'It protects source data and makes reports easier to refresh', 'It changes the file type', 'It prevents sorting'],
      correct_index: 1,
      explanation: 'Separating raw data from reporting reduces accidental edits and keeps workflows clearer.',
      order_index: 3,
    },
  ],
  'quiz-dashboard-masterclass': [
    {
      id: 'question-dashboard-1',
      quiz_id: 'quiz-dashboard-masterclass',
      question: 'What should guide dashboard layout first?',
      options: ['The most colorful chart', 'The decision the dashboard supports', 'The largest logo', 'The number of tabs'],
      correct_index: 1,
      explanation: 'Dashboards are decision tools, so layout should emphasize what users need to decide.',
      order_index: 1,
    },
  ],
};

export const demoPodcasts: Podcast[] = [
  {
    id: 'podcast-1',
    title: 'Build weekly reports that people actually read',
    host: 'GTC Academy',
    description: 'A practical episode about short reporting cycles, KPIs, and visual hierarchy.',
    audio_url: null,
    thumbnail_url: null,
    duration_secs: 960,
    episode_number: 12,
    is_premium: false,
    is_published: true,
    published_at: now,
  },
  {
    id: 'podcast-2',
    title: 'From Excel chaos to reliable dashboards',
    host: 'GTC Academy',
    description: 'How to clean files, standardize inputs, and present numbers with less stress.',
    audio_url: null,
    thumbnail_url: null,
    duration_secs: 1180,
    episode_number: 11,
    is_premium: true,
    is_published: true,
    published_at: now,
  },
];

export const demoTemplates: Template[] = [
  {
    id: 'template-budget',
    title: 'Monthly Budget Tracker',
    description: 'A clean Excel template for planned vs actual spending.',
    type: 'xlsx',
    file_url: null,
    thumbnail: null,
    file_size: '84 KB',
    is_premium: false,
    downloads: 410,
    category_id: 'cat-excel',
    category: demoCategories[0],
  },
  {
    id: 'template-sales-dashboard',
    title: 'Sales KPI Dashboard',
    description: 'Dashboard structure for revenue, margin, pipeline, and conversion.',
    type: 'xlsx',
    file_url: null,
    thumbnail: null,
    file_size: '156 KB',
    is_premium: true,
    downloads: 238,
    category_id: 'cat-bi',
    category: demoCategories[2],
  },
];

export const demoCertificates: Certificate[] = [
  {
    id: 'certificate-demo',
    user_id: demoProfile.id,
    course_id: 'course-excel-foundations',
    cert_id: 'GTC-2026-XL-001',
    pdf_url: null,
    qr_url: null,
    status: 'issued',
    issued_at: now,
    course: demoCourses[0],
    profile: demoProfile,
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: demoProfile.id,
    type: 'course',
    title: 'Continue your Excel course',
    body: 'You are more than halfway through Excel Foundations.',
    image_url: null,
    deep_link: null,
    read: false,
    sent_at: now,
  },
  {
    id: 'notif-2',
    user_id: null,
    type: 'system',
    title: 'New dashboard template',
    body: 'A premium sales dashboard template is now available.',
    image_url: null,
    deep_link: null,
    read: true,
    sent_at: now,
  },
];

export const demoStats = {
  totalUsers: 4280,
  certificates: 314,
  activeSubs: 786,
};

export function findDemoCourse(courseId: string) {
  return demoCourses.find(course => course.id === courseId) ?? null;
}
